### ISSUE TITLE
Allow SIEGE ENGINE optional rules for prime/secondary

### ISSUE THREAD

**Issue by cal413** [switchspan/foundryvtt-cnc#2]
There's some optional rules in the CK Guide, for example using the Challenge Base of 18 for everything and applying a +6 for prime attributes is an easy variant for the SIEGE ENGINE.

**Comment by switchspan** [comment]
> There's some optional rules in the CK Guide, for example uysing the Challenge Base of 18 for everything and applying a +6 for prime attributes is an easy variant for the SIEGE ENGINE.

That is a good idea -- are you talking about p.275 in the CK Guide? Maybe this can even be a system option (Game Settings->Configure Settings->System Settings)? I took out some of the D&D 5e ones that didn't really apply, but this sounds like a good candidate for a system setting that has maybe a true/false or on/off option?
I was also considering adding checkboxes to the character sheet to mark primary/secondary and maybe add in the logic to handle the number of them depending on race later (human 3 primary/demi-human 2 primary).

**Comment by HiHo01** [comment]
I'd be working on the base rules first i.e Players handbook only, but using the Calculation as per cal413 comment above which basically does the same things just in a different way.
I'd probably include the expanded classes from the CKG and attribute extensions up to 30. Beauty should be an option for later.
As for a checkbox for the Prime and secondary attributes. Yep, Just one for a Prime would be good (giving you the +6 on your checks).
I wouldn't restrict the number of Prime attributes for races as players ad keepers should just control this.

**Comment by Levendor68** [comment]
I agree that the Challenge Base 18 would probably be the best way to handle Siege Engine... 

If the idea is to transform the 5e sheets into C&C, then there are 5e attribute modifiers, proficiency and proficiency bonus, and attribute check-bonus and save-bonus fields (and probably more on the bloated 5e sheet!). We could click on proficiency for the 2 or 3 attributes that are prime (I've already got the on/off primes working for the monsters/npc sheet), and then hack the 5e functionality to make the proficiency bonus a static +6. The attribute check-bonus and save-bonus could each be set to the monsters Hit Dice for NPCs. 

A pc would get d20 + attribute modifier {{attribute.{ID}.mod}} + level (for a save or a normal check)  +  proficiency (static +6 if a Prime, 0 if non-prime).

An npc would get d20 + Hit Dice (5e's CR field)  +  proficiency (static +6 if a Prime, 0 if non-prime).

Rather than considering as an option rule, it's just another way of coding the Base 12/Base 18 Siege Engine as a Base 18/Base 18... the rolls and results are the same.

(I'm a noob here... I'm sure you all were already way past this, but it helped me to think my way through it).

**Comment by switchspan** [comment]
moving effort to the TLG repo: https://gitlab.com/troll-lord/foundry-vtt/ruleset/castles-and-crusades
